# Generated by Django 6.0b1 on 2025-11-05 02:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.CharField(max_length=200)),
                ('sistema_coordenadas', models.CharField(choices=[('WGS84', 'WGS84 (GPS)'), ('UTM', 'Universal Transverse Mercator'), ('LOCAL', 'Sistema Local')], default='UTM', max_length=10)),
                ('zona_utm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('hemisferio', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur')], max_length=1, null=True)),
                ('lat_referencia', models.FloatField(help_text='Latitud del punto de referencia')),
                ('lon_referencia', models.FloatField(help_text='Longitud del punto de referencia')),
                ('elevacion_referencia', models.FloatField(default=0, help_text='Elevación sobre nivel del mar (m)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLAN', 'Planificación'), ('EJECUCION', 'En Ejecución'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='PLAN', max_length=20)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_dirigidos', to=settings.AUTH_USER_MODEL)),
                ('residente_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_residencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElementoConstructivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ZAPATA', 'Zapata'), ('COLUMNA', 'Columna'), ('TRABE', 'Trabe/Viga'), ('MURO', 'Muro'), ('LOSA', 'Losa'), ('CIMENTACION', 'Cimentación'), ('PAVIMENTO', 'Pavimento'), ('TERRACERIA', 'Terracería'), ('DRENAJE', 'Drenaje'), ('OTRO', 'Otro')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('elevacion', models.FloatField(help_text='Elevación en metros')),
                ('utm_este', models.FloatField(blank=True, null=True)),
                ('utm_norte', models.FloatField(blank=True, null=True)),
                ('utm_zona', models.IntegerField(blank=True, null=True)),
                ('area_proyecto', models.FloatField(blank=True, help_text='Área en m²', null=True)),
                ('volumen_proyecto', models.FloatField(blank=True, help_text='Volumen en m³', null=True)),
                ('longitud_proyecto', models.FloatField(blank=True, help_text='Longitud en m', null=True)),
                ('porcentaje_avance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REPLANTEO', 'En Replanteo'), ('EXCAVACION', 'Excavación'), ('CIMBRADO', 'Cimbrado'), ('ARMADO', 'Armado de Acero'), ('COLADO', 'Colado'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio_programada', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_programada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_responsable', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='sisgestionobras.proyecto')),
            ],
            options={
                'verbose_name': 'Elemento Constructivo',
                'verbose_name_plural': 'Elementos Constructivos',
                'ordering': ['codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud_actual', models.FloatField(blank=True, null=True)),
                ('longitud_actual', models.FloatField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('jefe_cuadrilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('elemento_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_trabajando', to='sisgestionobras.elementoconstructivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrillas', to='sisgestionobras.proyecto')),
            ],
            options={
                'verbose_name': 'Cuadrilla',
                'verbose_name_plural': 'Cuadrillas',
            },
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_punto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('BENCHMARK', 'Banco de Nivel'), ('REPLANTEO', 'Punto de Replanteo'), ('VERIFICACION', 'Verificación'), ('CONTROL', 'Control de Calidad'), ('LEVANTAMIENTO', 'Levantamiento')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('elevacion', models.FloatField()),
                ('precision_horizontal', models.FloatField(blank=True, help_text='Precisión horizontal en cm', null=True)),
                ('precision_vertical', models.FloatField(blank=True, help_text='Precisión vertical en cm', null=True)),
                ('equipo_medicion', models.CharField(choices=[('GPS_DIFERENCIAL', 'GPS Diferencial'), ('GPS_RTK', 'GPS RTK'), ('ESTACION_TOTAL', 'Estación Total'), ('NIVEL', 'Nivel Óptico'), ('GPS_MOVIL', 'GPS Móvil')], max_length=30)),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='sisgestionobras.elementoconstructivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_control', to='sisgestionobras.proyecto')),
                ('topografo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Control',
                'verbose_name_plural': 'Puntos de Control',
                'ordering': ['-fecha_medicion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('avance_cantidad', models.FloatField(help_text='Cantidad ejecutada en la unidad del concepto')),
                ('avance_porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes_avance/')),
                ('descripcion', models.TextField()),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('personal_asignado', models.IntegerField(default=0)),
                ('horas_trabajadas', models.FloatField(default=0)),
                ('validado', models.BooleanField(default=False)),
                ('cuadrilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='sisgestionobras.cuadrilla')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='sisgestionobras.elementoconstructivo')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Avance',
                'verbose_name_plural': 'Reportes de Avance',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='VolumenTerraceria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('area_m2', models.FloatField()),
                ('volumen_corte_m3', models.FloatField(default=0)),
                ('volumen_relleno_m3', models.FloatField(default=0)),
                ('volumen_neto_m3', models.FloatField(default=0)),
                ('metodo_calculo', models.CharField(choices=[('SECCIONES', 'Áreas de Secciones'), ('GRID', 'Retícula (Grid)'), ('TIN', 'Triangulación (TIN)'), ('CURVAS', 'Curvas de Nivel')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('archivo_levantamiento', models.FileField(blank=True, help_text='Archivo CSV con coordenadas del levantamiento', null=True, upload_to='levantamientos/')),
                ('calculado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumenes', to='sisgestionobras.proyecto')),
            ],
            options={
                'verbose_name': 'Volumen de Terracería',
                'verbose_name_plural': 'Volúmenes de Terracería',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
